## This notebook is used to tune parameters for some classifier that will be used in our models.

In [1]:
from google.colab import drive
import numpy as np
import pandas as pd

GDRIVE_BASE_PATH = '/content/gdrive'
BASE_DATA_FOLDER_PATH = f'{GDRIVE_BASE_PATH}/My Drive/project_scs3253/data'
RAW_DATA_FOLDER_PATH = f'{BASE_DATA_FOLDER_PATH}/raw_downloaded'

drive.mount(GDRIVE_BASE_PATH)

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [2]:

# Loading our project setup
HOME_DIR = '/content/gdrive/My Drive/project_scs3253'
% cd $HOME_DIR

from util.project_setup import ProjectSetup
import numpy as np
import pandas as pd

RANDOM_SEED = 1
np.random.seed(RANDOM_SEED)

CV_COUNT = 5

#SCORING_METRICS = 'f1'
SCORING_METRICS = 'accuracy'

/content/gdrive/My Drive/project_scs3253


In [3]:
import pandas as pd

# purposely don't want to use UserKey as index
df = pd.read_csv(f'{BASE_DATA_FOLDER_PATH}/filter_1000holdtime_1000obs_mildonly.csv', sep=',', index_col=0)
df = df.drop("userkey", axis=1)

print(df.shape)        
print(df.info())
df.head()

(84, 31)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 84 entries, 0 to 83
Data columns (total 31 columns):
hold_time_l_mean               84 non-null float64
hold_time_r_mean               84 non-null float64
hold_time_l_std                84 non-null float64
hold_time_r_std                84 non-null float64
hold_time_l_skew               84 non-null float64
hold_time_r_skew               84 non-null float64
hold_time_l_kurtosis           84 non-null float64
hold_time_r_kurtosis           84 non-null float64
hold_time_diff                 84 non-null float64
hold_time_diff_abs             84 non-null float64
latency_time_ll_mean           84 non-null float64
latency_time_rr_mean           84 non-null float64
latency_time_lr_mean           84 non-null float64
latency_time_rl_mean           84 non-null float64
latency_time_ll_std            84 non-null float64
latency_time_rr_std            84 non-null float64
latency_time_lr_std            84 non-null float64
latency_time_rl_std  

hold_time_l_mean  hold_time_r_mean  hold_time_l_std  hold_time_r_std  \
0         98.931818        101.595749        23.869914        37.219557   
1        153.702407        105.622423        53.213749        27.036622   
2        147.626087        167.039039        47.259923        56.045862   
3        125.093648        125.944823        21.344768        20.440962   
4        186.434423        141.827793        61.740463        43.035236   

   hold_time_l_skew  ...  latency_time_ll_rr_diff  latency_time_lr_rl_diff  \
0          0.236835  ...                40.979771               -18.540793   
1          0.264980  ...                25.711714                 2.742036   
2          0.666778  ...                34.890816                74.204668   
3          0.433463  ...               -32.314242                14.221029   
4          0.428770  ...                -4.639493               -75.820623   

   latency_time_ll_rr_diff_abs  latency_time_lr_rl_diff_abs  parkinsons  
0                    40.979771                    18.540793       False  
1                    25.711714                     2.742036       False  
2                    34.890816                    74.204668       False  
3                    32.314242                    14.221029        True  
4                     4.639493                    75.820623       False  

[5 rows x 31 columns]

In [4]:
y = df['parkinsons']
X_orig = df.drop([
             "parkinsons"], axis=1)

X=X_orig
print(X.shape, y.shape)

(84, 30) (84,)


In [0]:
# # Break X into 2 tables, one contains the holdtime related features and another for latency related features
# table_break_index = X.columns.get_loc("latency_time_ll_mean")
  
# X_holdtime = X.iloc[: , 0:table_break_index]

# X_latency = X.iloc[: , table_break_index:-1]


In [5]:
#split datas
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=RANDOM_SEED, stratify=y)

print("X", X_train.shape, X_test.shape, y_train.shape, y_test.shape)

print("Parkinsons:\n", df['parkinsons'].value_counts())

X (67, 30) (17, 30) (67,) (17,)
Parkinsons:
 True     43
False    41
Name: parkinsons, dtype: int64


In [0]:
# X_test_orig = X_test
# y_test_orig = y_test

In [7]:
# See the breakdown of parkinson users
print("y_train:", y_train.shape, y_train.sum())
print("y_test:", y_test.shape, y_test.sum())

y_train: (67,) 34
y_test: (17,) 9


In [0]:

# from collections import Counter
# from imblearn.over_sampling import SMOTE # doctest: +NORMALIZE_WHITESPACE


# sm = SMOTE()
# X1_res, y1_res = sm.fit_resample(X_train, np.ravel(y_train))

# print('Resampled dataset shape %s' % Counter(y1_res))

# X_train = X1_res
# y_train = y1_res

# print(X_train.shape, y_train.shape)

In [9]:
X.head()

hold_time_l_mean  hold_time_r_mean  hold_time_l_std  hold_time_r_std  \
0         98.931818        101.595749        23.869914        37.219557   
1        153.702407        105.622423        53.213749        27.036622   
2        147.626087        167.039039        47.259923        56.045862   
3        125.093648        125.944823        21.344768        20.440962   
4        186.434423        141.827793        61.740463        43.035236   

   hold_time_l_skew  ...  latency_time_rl_kurtosis  latency_time_ll_rr_diff  \
0          0.236835  ...                 -0.917784                40.979771   
1          0.264980  ...                 -0.709928                25.711714   
2          0.666778  ...                 -0.844957                34.890816   
3          0.433463  ...                 -0.929236               -32.314242   
4          0.428770  ...                  1.710421                -4.639493   

   latency_time_lr_rl_diff  latency_time_ll_rr_diff_abs  \
0               -18.540793                    40.979771   
1                 2.742036                    25.711714   
2                74.204668                    34.890816   
3                14.221029                    32.314242   
4               -75.820623                     4.639493   

   latency_time_lr_rl_diff_abs  
0                    18.540793  
1                     2.742036  
2                    74.204668  
3                    14.221029  
4                    75.820623  

[5 rows x 30 columns]

In [10]:
# import numpy as np
from sklearn.preprocessing import PolynomialFeatures


# use degree=2 as it is the best between no poly and degree=3
poly_X = PolynomialFeatures(1)
X_train = poly_X.fit_transform(X_train)
X_test  = poly_X.transform(X_test)
#X_test_orig  = poly_X.transform(X_test_orig)


print("X", X_train.shape, X_test.shape, y_train.shape, y_test.shape)


X (67, 31) (17, 31) (67,) (17,)


In [11]:
# Scale the training set
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import normalize, Normalizer

def running_scaler(X_tr, X_te):
  
  #scaler = StandardScaler()
  scaler = Normalizer()
  
  scaler.fit(X_tr)

  X_train_sc = scaler.transform(X_tr)
  X_test_sc = scaler.transform(X_te)
  
  print(X_train_sc.shape, X_test_sc.shape) 

  return X_train_sc, X_test_sc


X_train, X_test = running_scaler(X_train, X_test)







(67, 31) (17, 31)


In [0]:
import numpy as np

from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, classification_report, roc_auc_score, precision_score, recall_score


def print_metrics(name_str, y_true, y_pred):
  print("  ====", name_str, "===============")
  conf_m = confusion_matrix(y_true, y_pred)
  tn, fp, fn, tp = conf_m.ravel()
  print(conf_m)
  #print(classification_report(y_true, y_pred, labels=None))
  #print(precision_recall_fscore_support(y_true, y_pred))

  #Specificity = TN/(TN + FP) 
  specificity = tn/(tn+fp)
 
  print("\nf1:          {0:12.6f}, "
        "\nprecision:   {1:12.6f}, "
        "\nrecall:      {2:12.6f}, "
        "\nAccuracy:    {3:12.6f}, "
        "\nAuc:         {4:12.6f}  "
        "\nSpecificity: {5:12.6f}  ".format(
          f1_score(y_true, y_pred),
          precision_score(y_true, y_pred),
          recall_score(y_true, y_pred),
          accuracy_score(y_true, y_pred),
          roc_auc_score(y_true, y_pred),
          specificity)) 


In [0]:
from sklearn.ensemble import VotingClassifier

def voting_results(dataset_name, X_tr, X_te, y_tr, y_te, list_of_classifier=[]):
  
  voting_option = ['hard', 'soft']

  #print("-------- ", dataset_name )
  for option in voting_option:
    eclf_1 = VotingClassifier(estimators=list_of_classifier, voting=option)

    eclf_1 = eclf_1.fit(X_tr, y_tr)

    print("=== Using Voting:", option)

    print_metrics("X_train ("+ option + ")", y_tr, eclf_1.predict(X_tr))

    print_metrics("X_test ("+ option + ")" , y_te, eclf_1.predict(X_te))
    
    
#voting_results("All features", X_train, X_test, y_train, y_test, list_of_all_features_classifier)  

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier

knn = KNeighborsClassifier()
print("KNeighborsClassifier Train score:\n", cross_val_score(knn, X_train, y_train, scoring=SCORING_METRICS, cv=CV_COUNT)) 
knn.fit(X_train, y_train)
# knn_pred_parkinsons = knn.predict(X_test)
# print_metrics("KNN", y_test1, knn_pred_parkinsons)

dt_clf = DecisionTreeClassifier(random_state=RANDOM_SEED)
print("\nDecisionTreeClassifier Train score:\n", cross_val_score(dt_clf, X_train, y_train, scoring=SCORING_METRICS, cv=CV_COUNT)) 
dt_clf.fit(X_train, y_train)
# dt_pred_parkinsons = dt_clf.predict(X_test)
# print_metrics("Decision Tree", y_test, dt_pred_parkinsons)

rf_clf = RandomForestClassifier(n_estimators=100, random_state=RANDOM_SEED)
print("\nRandomForestClassifier Train score:\n", cross_val_score(rf_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 
rf_clf.fit(X_train, y_train)
# rf_pred_parkinsons = rf_clf.predict(X_test)
# print_metrics("Random Forest", y_test, rf_pred_parkinsons)

lr_clf = LogisticRegression(solver='lbfgs', max_iter=1000, random_state=RANDOM_SEED)
print("\nLogisticRegression Train score:\n", cross_val_score(lr_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 
lr_clf.fit(X_train, y_train)
# lr_pred_parkinsons = lr_clf.predict(X_test)
# print_metrics("Logistic Regression", y_test, lr_pred_parkinsons)

from sklearn.svm import SVC
svc_clf = SVC(gamma="auto", random_state=RANDOM_SEED)
print("\nSVC Train score:\n", cross_val_score(svc_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 
svc_clf.fit(X_train, y_train)
# svc_pred_parkinsons = svc_clf.predict(X_test)
# print_metrics("SVM", y_test, svc_pred_parkinsons)

ada_clf = AdaBoostClassifier(random_state=RANDOM_SEED)
print("\nAdaBoostClassifier Train score:\n", cross_val_score(ada_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 
ignored = ada_clf.fit(X_train, y_train)
#ada_pred_parkinsons = ada_clf.predict(X_test)
#print_metrics("Adaboost", y_test, ada_pred_parkinsons)


from xgboost import XGBClassifier
xgb_clf = XGBClassifier(random_state=RANDOM_SEED)
print("\nXGBClassifier Train score:\n", cross_val_score(xgb_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 
ignored = xgb_clf.fit(X_train, y_train)
#xgb_pred_parkinsons = ada_clf.predict(X_test)
#print_metrics("xgboost", y_test, xgb_pred_parkinsons)


KNeighborsClassifier Train score:
 [0.21428571 0.42857143 0.57142857 0.46153846 0.58333333]

DecisionTreeClassifier Train score:
 [0.35714286 0.57142857 0.57142857 0.46153846 0.58333333]

RandomForestClassifier Train score:
 [0.42857143 0.57142857 0.64285714 0.53846154 0.66666667]

LogisticRegression Train score:
 [0.35714286 0.42857143 0.57142857 0.61538462 0.66666667]

SVC Train score:
 [0.5        0.5        0.5        0.61538462 0.5       ]

AdaBoostClassifier Train score:
 [0.28571429 0.5        0.71428571 0.53846154 0.66666667]

XGBClassifier Train score:
 [0.5        0.5        0.64285714 0.61538462 0.58333333]


In [15]:
X_test1 = X_test
y_test1 = y_test

print("Before any tuning, test scores:")
print(X_test1.shape, y_test1.shape)

#y_always_false = np.zeros(y_test.shape)
y_always_true = np.ones(y_test1.shape)
#y_always_false[0] = True # just to make f1 value
print_metrics("Always true", y_test1, y_always_true)
#print_metrics("Always false", y_test, y_always_false)

knn_pred_parkinsons = knn.predict(X_test1)
print_metrics("KNN", y_test1, knn_pred_parkinsons)

rf_pred_parkinsons = rf_clf.predict(X_test1)
print_metrics("Random Forest", y_test1, rf_pred_parkinsons)

dt_pred_parkinsons = dt_clf.predict(X_test1)
print_metrics("Decision Tree", y_test1, dt_pred_parkinsons)

lr_pred_parkinsons = lr_clf.predict(X_test1)
print_metrics("Logistic Regression", y_test1, lr_pred_parkinsons)

svc_pred_parkinsons = svc_clf.predict(X_test1)
print_metrics("SVC", y_test1, svc_pred_parkinsons)

ada_pred_parkinsons = ada_clf.predict(X_test1)
print_metrics("Adaboost", y_test1, ada_pred_parkinsons)

xgb_pred_parkinsons = ada_clf.predict(X_test1)
print_metrics("xgboost", y_test1, xgb_pred_parkinsons)

Before any tuning, test scores:
(17, 31) (17,)
  ==== Always true ===============
[[0 8]
 [0 9]]

f1:              0.692308, 
precision:       0.529412, 
recall:          1.000000, 
Accuracy:        0.529412, 
Auc:             0.500000  
Specificity:     0.000000  
  ==== KNN ===============
[[4 4]
 [3 6]]

f1:              0.631579, 
precision:       0.600000, 
recall:          0.666667, 
Accuracy:        0.588235, 
Auc:             0.583333  
Specificity:     0.500000  
  ==== Random Forest ===============
[[4 4]
 [1 8]]

f1:              0.761905, 
precision:       0.666667, 
recall:          0.888889, 
Accuracy:        0.705882, 
Auc:             0.694444  
Specificity:     0.500000  
  ==== Decision Tree ===============
[[6 2]
 [4 5]]

f1:              0.625000, 
precision:       0.714286, 
recall:          0.555556, 
Accuracy:        0.647059, 
Auc:             0.652778  
Specificity:     0.750000  
  ==== Logistic Regression ===============
[[3 5]
 [1 8]]

f1:              0.727

In [0]:
#@title
# # testing Orig y_test
# #X_test = X1_res
# #y_test = y1_res
# X_test1 = X_test_orig
# y_test1 = y_test_orig

# print(X_test1.shape, y_test1.shape)

# #y_always_false = np.zeros(y_test.shape)
# y_always_true = np.ones(y_test1.shape)
# #y_always_false[0] = True # just to make f1 value
# print_metrics("Always true", y_test1, y_always_true)
# #print_metrics("Always false", y_test, y_always_false)

# knn_pred_parkinsons = knn.predict(X_test1)
# print_metrics("KNN", y_test1, knn_pred_parkinsons)

# rf_pred_parkinsons = rf_clf.predict(X_test1)
# print_metrics("Random Forest", y_test1, rf_pred_parkinsons)

# dt_pred_parkinsons = dt_clf.predict(X_test1)
# print_metrics("Decision Tree", y_test1, dt_pred_parkinsons)

# lr_pred_parkinsons = lr_clf.predict(X_test1)
# print_metrics("Logistic Regression", y_test1, lr_pred_parkinsons)

# svm_pred_parkinsons = svm_clf.predict(X_test1)
# print_metrics("SVM", y_test1, svm_pred_parkinsons)


## Using grid search to fine tune models 

### Fine tune SVC

In [16]:
from sklearn.model_selection import GridSearchCV

svc_clf = SVC(random_state=RANDOM_SEED)

param_grid1 = {
              'C' : [0.01, 0.1, 0.5, 1, 10, 20, 50, 100, 1000],  
              'decision_function_shape': ['ovo', 'ovr'],
              'gamma': ['auto', 'scale'],
              'kernel' : ['poly', 'rbf'],
              'degree' : [2, 3], 
              'probability' :[True, False]  }


grid_search = GridSearchCV(svc_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train,  y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)



0.5970149253731343
SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=True, random_state=1, shrinking=True, tol=0.001,
    verbose=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [36]:
# use the best parameter found
svc_clf = SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=True, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

print("Train score:", cross_val_score(svc_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 

svc_clf.fit(X_train, y_train)

svc_pred_parkinsons = svc_clf.predict(X_test)
print_metrics("SVC", y_test, svc_pred_parkinsons)

Train score: [0.5        0.42857143 0.71428571 0.53846154 0.83333333]
  ==== SVC ===============
[[4 4]
 [4 5]]

f1:              0.555556, 
precision:       0.555556, 
recall:          0.555556, 
Accuracy:        0.529412, 
Auc:             0.527778  
Specificity:     0.500000  


###  Fine tune Decision Tree

In [18]:
# Fine tune decision tree
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

dt_clf =  DecisionTreeClassifier(random_state=RANDOM_SEED)

param_grid1 = { 
              'criterion' : ['gini', 'entropy'],  
              'max_depth': [2, 3, 7],
              'splitter' : ['best', 'random'],
              'min_samples_split': [2]
}


grid_search = GridSearchCV(dt_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)

0.5671641791044776
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1, splitter='best')


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [37]:


dt_clf =DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1, splitter='best')


print("Train score:", cross_val_score(dt_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 


dt_clf.fit(X_train, y_train)

dt_pred_parkinsons = dt_clf.predict(X_test)
print_metrics("Decision Tree", y_test, dt_pred_parkinsons)

Train score: [0.57142857 0.64285714 0.57142857 0.46153846 0.58333333]
  ==== Decision Tree ===============
[[5 3]
 [4 5]]

f1:              0.588235, 
precision:       0.625000, 
recall:          0.555556, 
Accuracy:        0.588235, 
Auc:             0.590278  
Specificity:     0.625000  


## Fine tune GradientBoostingClassifier


In [50]:
from sklearn.ensemble import GradientBoostingClassifier

param_grid1 = {
      'loss': ['deviance', 'exponential'],
      'learning_rate':     [0.1, 1, 5, 10],
      'n_estimators' : [100],
      'criterion' : ['friedman_mse'],
      'max_depth' : [3, 5, 7, 9],
      'max_features' :['sqrt']
} 

gfb_clf = GradientBoostingClassifier(random_state=RANDOM_SEED)

grid_search = GridSearchCV(gfb_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)


0.6268656716417911
GradientBoostingClassifier(criterion='friedman_mse', init=None, learning_rate=5,
                           loss='exponential', max_depth=9, max_features='sqrt',
                           max_leaf_nodes=None, min_impurity_decrease=0.0,
                           min_impurity_split=None, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           presort='auto', random_state=1, subsample=1.0,
                           tol=0.0001, validation_fraction=0.1, verbose=0,
                           warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [51]:
grb_clf = GradientBoostingClassifier(criterion='friedman_mse', init=None, learning_rate=5,
                           loss='exponential', max_depth=9, max_features='sqrt',
                           max_leaf_nodes=None, min_impurity_decrease=0.0,
                           min_impurity_split=None, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           presort='auto', random_state=1, subsample=1.0,
                           tol=0.0001, validation_fraction=0.1, verbose=0,
                           warm_start=False)

print("Train score:", cross_val_score(grb_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 

grb_clf.fit(X_train, y_train)


grb_pred_parkinsons = grb_clf.predict(X_test)

print_metrics("grb_clf", y_test, grb_pred_parkinsons)

Train score: [0.64285714 0.57142857 0.64285714 0.53846154 0.75      ]
  ==== grb_clf ===============
[[7 1]
 [4 5]]

f1:              0.666667, 
precision:       0.833333, 
recall:          0.555556, 
Accuracy:        0.705882, 
Auc:             0.715278  
Specificity:     0.875000  


### Fine tune KNN

In [20]:
# Fine tune decision tree
from sklearn.model_selection import GridSearchCV

knn = KNeighborsClassifier()

param_grid1 = {
              'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
              'n_neighbors': [2, 3, 4, 5, 7],
              'p': [1, 2, 3],
              'leaf_size' : [2, 3, 4, 5], 
              'weights' : ['uniform', 'distance']
} 


grid_search = GridSearchCV(knn, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)

0.6268656716417911
KNeighborsClassifier(algorithm='auto', leaf_size=2, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=1,
                     weights='distance')


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [38]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(algorithm='auto', leaf_size=2, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=1,
                     weights='distance')

print("Train score:", cross_val_score(knn, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 

knn.fit(X_train, y_train)


knn_pred_parkinsons = knn.predict(X_test)

print_metrics("KNN", y_test, knn_pred_parkinsons)

Train score: [0.42857143 0.78571429 0.57142857 0.53846154 0.83333333]
  ==== KNN ===============
[[5 3]
 [3 6]]

f1:              0.666667, 
precision:       0.666667, 
recall:          0.666667, 
Accuracy:        0.647059, 
Auc:             0.645833  
Specificity:     0.625000  


### Fine tune random forest

In [22]:
# Fine tune random forest
from sklearn.model_selection import GridSearchCV

rf_clf = RandomForestClassifier(random_state=RANDOM_SEED)

param_grid1 = {
  'criterion':         ['gini', 'entropy'],
  'max_features':      ['auto','sqrt', 'log2'],
  'bootstrap':         [True, False],
  'n_estimators':      [50, 100, 150, 200],
  'max_depth':         [5, 7, 10],
  'min_samples_split': [2],
  'min_samples_leaf':  [3, 5, 7],
}


grid_search = GridSearchCV(rf_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)

0.6119402985074627
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=5, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [39]:
rf_clf = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=5, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

print("Train score:", cross_val_score(rf_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 

rf_clf.fit(X_train, y_train)
rf_pred_parkinsons = rf_clf.predict(X_test)
print_metrics("Random Forest", y_test, rf_pred_parkinsons)

Train score: [0.57142857 0.64285714 0.64285714 0.53846154 0.66666667]
  ==== Random Forest ===============
[[5 3]
 [2 7]]

f1:              0.736842, 
precision:       0.700000, 
recall:          0.777778, 
Accuracy:        0.705882, 
Auc:             0.701389  
Specificity:     0.625000  


### Fine tune Logistic Regression

In [24]:
# Fine tune decision tree
from sklearn.model_selection import GridSearchCV

lr_clf = LogisticRegression(random_state=RANDOM_SEED)

param_grid1 = {
              'solver': ['lbfgs', 'liblinear'],
              'multi_class': ['ovr'],
              'max_iter' : [1000],
              'C' : [0.1, 0.9, 1, 10]
 
}

grid_search = GridSearchCV(lr_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)

0.5373134328358209
LogisticRegression(C=0.9, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=1,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [40]:
from sklearn.linear_model import LogisticRegression
lr_clf = LogisticRegression(C=0.9, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='ovr', n_jobs=None, penalty='l2', random_state=1,
                   solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

lr_clf.fit(X_train, y_train)

lr_pred_parkinsons = lr_clf.predict(X_test)
print_metrics("Logistic Regression", y_test, lr_pred_parkinsons)

  ==== Logistic Regression ===============
[[3 5]
 [1 8]]

f1:              0.727273, 
precision:       0.615385, 
recall:          0.888889, 
Accuracy:        0.647059, 
Auc:             0.631944  
Specificity:     0.375000  


## Fine tune Adaboost

In [42]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(random_state=RANDOM_SEED)

param_grid1 = {
  'n_estimators':      [50, 100, 150],
  'learning_rate':     [0.01, 0.1, 1],
  'algorithm': ['SAMME', 'SAMME.R'],
}

grid_search = GridSearchCV(ada_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)

0.5970149253731343
AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.1,
                   n_estimators=100, random_state=1)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [41]:
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.1,
                   n_estimators=100, random_state=1)

ada_clf.fit(X_train, y_train)

ada_pred_parkinsons = ada_clf.predict(X_test)
print_metrics("Adaboost", y_test, ada_pred_parkinsons)

  ==== Adaboost ===============
[[6 2]
 [4 5]]

f1:              0.625000, 
precision:       0.714286, 
recall:          0.555556, 
Accuracy:        0.647059, 
Auc:             0.652778  
Specificity:     0.750000  


## Fine tune xgboost

In [28]:
from sklearn.model_selection import GridSearchCV

from xgboost import XGBClassifier

xgb_clf = XGBClassifier(random_state=RANDOM_SEED)

param_grid1 = {
  'max_depth':         [2, 3, 5],
  'learning_rate':     [0.1, 1, 10],
  'n_estimators':      [10, 20, 50], 
  #'booster':           ['gbtree', 'gblinear', 'dart'], 
  'booster':           ['gbtree'],
  'gamma':             [0.0001, 0.001, 0.01, 0.1],   
    
#   'max_features':      ['auto','sqrt', 'log2'],
#   'bootstrap':         [True, False],
}

# min_child_weight (int) – Minimum sum of instance weight(hessian) needed in a child.

# max_delta_step (int) – Maximum delta step we allow each tree’s weight estimation to be.

# subsample (float) – Subsample ratio of the training instance.

# colsample_bytree (float) – Subsample ratio of columns when constructing each tree.

# colsample_bylevel (float) – Subsample ratio of columns for each level.

# colsample_bynode (float) – Subsample ratio of columns for each split.

# reg_alpha (float (xgb's alpha)) – L1 regularization term on weights

# reg_lambda (float (xgb's lambda)) – L2 regularization term on weights

# scale_pos_weight (float) – Balancing of positive and negative weights.

# base_score – The initial prediction score of all instances, global bias.

# seed (int) – Random number seed. (Deprecated, please use random_state)

# random_state (int) – Random number seed. (replaces seed)

# missing (float, optional) – Value in the data which needs to be present as a missing value. If None, defaults to np.nan.

# importance_type (string, default "gain") – The feature importance type for the feature_importances_ property: either “gain”, “weight”, “cover”, “total_gain” or “total_cover”.

# **kwargs (dict, optional) –



grid_search = GridSearchCV(xgb_clf, param_grid =param_grid1, cv=CV_COUNT, scoring=SCORING_METRICS)
grid_search.fit(X_train, y_train)

#print(ramdomgrid_search)
# summarize the results of the random parameter search
print(grid_search.best_score_)
print(grid_search.best_estimator_)

0.6567164179104478
XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0.001,
              learning_rate=1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=20, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [29]:

xgb_clf = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0.001,
              learning_rate=1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=20, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)


print("\nXGBClassifier Train score:\n", cross_val_score(xgb_clf, X_train, y_train,  scoring=SCORING_METRICS, cv=CV_COUNT)) 
ignored = xgb_clf.fit(X_train, y_train)

xgb_pred_parkinsons = xgb_clf.predict(X_test)
print_metrics("XGBClassifier", y_test, xgb_pred_parkinsons)



XGBClassifier Train score:
 [0.57142857 0.71428571 0.64285714 0.53846154 0.83333333]
  ==== XGBClassifier ===============
[[5 3]
 [2 7]]

f1:              0.736842, 
precision:       0.700000, 
recall:          0.777778, 
Accuracy:        0.705882, 
Auc:             0.701389  
Specificity:     0.625000  


In [30]:
X_test1 = X_test
y_test1 = y_test

print("After tuned")

#y_always_false = np.zeros(y_test.shape)
y_always_true = np.ones(y_test1.shape)
#y_always_false[0] = True # just to make f1 value
print_metrics("Always true", y_test1, y_always_true)
#print_metrics("Always false", y_test, y_always_false)

knn_pred_parkinsons = knn.predict(X_test1)
print_metrics("KNN", y_test1, knn_pred_parkinsons)

rf_pred_parkinsons = rf_clf.predict(X_test1)
print_metrics("Random Forest", y_test1, rf_pred_parkinsons)

dt_pred_parkinsons = dt_clf.predict(X_test1)
print_metrics("Decision Tree", y_test1, dt_pred_parkinsons)

lr_pred_parkinsons = lr_clf.predict(X_test1)
print_metrics("Logistic Regression", y_test1, lr_pred_parkinsons)

svc_pred_parkinsons = svc_clf.predict(X_test1)
print_metrics("SVC", y_test1, svc_pred_parkinsons)

ada_pred_parkinsons = ada_clf.predict(X_test1)
print_metrics("Adaboost", y_test1, ada_pred_parkinsons)

xgb_pred_parkinsons = ada_clf.predict(X_test1)
print_metrics("xgboost", y_test1, xgb_pred_parkinsons)


After tuned
  ==== Always true ===============
[[0 8]
 [0 9]]

f1:              0.692308, 
precision:       0.529412, 
recall:          1.000000, 
Accuracy:        0.529412, 
Auc:             0.500000  
Specificity:     0.000000  
  ==== KNN ===============
[[4 4]
 [5 4]]

f1:              0.470588, 
precision:       0.500000, 
recall:          0.444444, 
Accuracy:        0.470588, 
Auc:             0.472222  
Specificity:     0.500000  
  ==== Random Forest ===============
[[5 3]
 [4 5]]

f1:              0.588235, 
precision:       0.625000, 
recall:          0.555556, 
Accuracy:        0.588235, 
Auc:             0.590278  
Specificity:     0.625000  
  ==== Decision Tree ===============
[[4 4]
 [3 6]]

f1:              0.631579, 
precision:       0.600000, 
recall:          0.666667, 
Accuracy:        0.588235, 
Auc:             0.583333  
Specificity:     0.500000  
  ==== Logistic Regression ===============
[[3 5]
 [1 8]]

f1:              0.727273, 
precision:       0.615385, 
r

In [0]:
from sklearn.ensemble import VotingClassifier

def voting_results(dataset_name, X_tr, X_te, y_tr, y_te, list_of_classifier=[]):
  
  voting_option = ['hard', 'soft']

  #print("-------- ", dataset_name )
  for option in voting_option:
    eclf_1 = VotingClassifier(estimators=list_of_classifier, voting=option)

    eclf_1 = eclf_1.fit(X_tr, y_tr)

    print("=== Using Voting:", option)

    print_metrics("X_train ("+ option + ")", y_tr, eclf_1.predict(X_tr))

    print_metrics("X_test ("+ option + ")" , y_te, eclf_1.predict(X_te))
    
    
#voting_results("All features", X_train, X_test, y_train, y_test, all_features_clf_list)  

In [32]:
from sklearn.ensemble import VotingClassifier


all_features_clf_list = [  ('knn', knn), 
                           ('rf', rf_clf), 
                           ('dt', dt_clf), 
                           ('lr', lr_clf), 
                           ('svc', svc_clf),
                           ('ada', ada_clf),
                           ('xgb', xgb_clf)]

voting_results("All features", X_train, X_test, y_train, y_test, all_features_clf_list)  


=== Using Voting: hard
  ==== X_train (hard) ===============
[[33  0]
 [ 0 34]]

f1:              1.000000, 
precision:       1.000000, 
recall:          1.000000, 
Accuracy:        1.000000, 
Auc:             1.000000  
Specificity:     1.000000  
  ==== X_test (hard) ===============
[[3 5]
 [4 5]]

f1:              0.526316, 
precision:       0.500000, 
recall:          0.555556, 
Accuracy:        0.470588, 
Auc:             0.465278  
Specificity:     0.375000  
=== Using Voting: soft
  ==== X_train (soft) ===============
[[33  0]
 [ 0 34]]

f1:              1.000000, 
precision:       1.000000, 
recall:          1.000000, 
Accuracy:        1.000000, 
Auc:             1.000000  
Specificity:     1.000000  
  ==== X_test (soft) ===============
[[2 6]
 [4 5]]

f1:              0.500000, 
precision:       0.454545, 
recall:          0.555556, 
Accuracy:        0.411765, 
Auc:             0.402778  
Specificity:     0.250000  


In [0]:
# After tuned (accuracy)
#   ==== Always true ===============
# [[0 8]
#  [0 9]]

# f1:              0.692308, 
# precision:       0.529412, 
# recall:          1.000000, 
# Accuracy:        0.529412, 
# Auc:             0.500000  
# Specificity:     0.000000  
#   ==== KNN ===============
# [[1 7]
#  [2 7]]

# f1:              0.608696, 
# precision:       0.500000, 
# recall:          0.777778, 
# Accuracy:        0.470588, 
# Auc:             0.451389  
# Specificity:     0.125000  
#   ==== Random Forest ===============
# [[5 3]
#  [2 7]]

# f1:              0.736842, 
# precision:       0.700000, 
# recall:          0.777778, 
# Accuracy:        0.705882, 
# Auc:             0.701389  
# Specificity:     0.625000  
#   ==== Decision Tree ===============
# [[6 2]
#  [3 6]]

# f1:              0.705882, 
# precision:       0.750000, 
# recall:          0.666667, 
# Accuracy:        0.705882, 
# Auc:             0.708333  
# Specificity:     0.750000  
#   ==== Logistic Regression ===============
# [[1 7]
#  [0 9]]

# f1:              0.720000, 
# precision:       0.562500, 
# recall:          1.000000, 
# Accuracy:        0.588235, 
# Auc:             0.562500  
# Specificity:     0.125000  
#   ==== SVC ===============
# [[3 5]
#  [2 7]]

# f1:              0.666667, 
# precision:       0.583333, 
# recall:          0.777778, 
# Accuracy:        0.588235, 
# Auc:             0.576389  
# Specificity:     0.375000  
#   ==== Adaboost ===============
# [[5 3]
#  [1 8]]

# f1:              0.800000, 
# precision:       0.727273, 
# recall:          0.888889, 
# Accuracy:        0.764706, 
# Auc:             0.756944  
# Specificity:     0.625000  
  
#   === Using Voting: hard
#   ==== X_train (hard) ===============
# [[32  1]
#  [ 0 34]]

# f1:              0.985507, 
# precision:       0.971429, 
# recall:          1.000000, 
# Accuracy:        0.985075, 
# Auc:             0.984848  
# Specificity:     0.969697  
#   ==== X_test (hard) ===============
# [[4 4]
#  [1 8]]

# f1:              0.761905, 
# precision:       0.666667, 
# recall:          0.888889, 
# Accuracy:        0.705882, 
# Auc:             0.694444  
# Specificity:     0.500000  
# === Using Voting: soft
#   ==== X_train (soft) ===============
# [[33  0]
#  [ 0 34]]

# f1:              1.000000, 
# precision:       1.000000, 
# recall:          1.000000, 
# Accuracy:        1.000000, 
# Auc:             1.000000  
# Specificity:     1.000000  
#   ==== X_test (soft) ===============
# [[4 4]
#  [2 7]]

# f1:              0.700000, 
# precision:       0.636364, 
# recall:          0.777778, 
# Accuracy:        0.647059, 
# Auc:             0.638889  
# Specificity:     0.500000  